export const ADD_CONTESTANT = 'ADD_CONTESTANT';
export const DELETE_MANAGER = 'DELETE_MANAGER';
export const UPDATE_MANAGER_PASSWORD = 'UPDATE_MANAGER_PASSWORD';
export const CONTESTANT_LIST = 'CONTESTANT_LIST';
export const CONTESTANT_TEAM_LIST = 'CONTESTANT_TEAM_LIST';
