export const ADD_MANAGER = 'ADD_MANAGER';
export const DELETE_MANAGER = 'DELETE_MANAGER';
export const UPDATE_MANAGER_PASSWORD = 'UPDATE_MANAGER_PASSWORD';
export const CREATE_MANAGER_ERROR = 'CREATE_MANAGER_ERROR';
export const VERIFY_MANAGER = 'VERIFY_MANAGER';
export const VERIFY_MANAGER_ERROR = 'VERIFY_MANAGER_ERROR';
export const JOIN_ROOM = 'JOIN_ROOM';
export const GET_RESPONSE = 'GET_RESPONSE';
export const MANAGER_DETAILS = 'MANAGER_DETAILS'

